src/Entity/Employer.php
<?php

namespace App\Entity;

use App\Repository\EmployerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmployerRepository::class)]
class Employer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Type(type:"App\Entity\Adresse")]
    #[Assert\Valid]
    private ?Adresse $Adresse = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->Adresse;
    }

    public function setAdresse(Adresse $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $anneeParution = null;

    #[ORM\Column]
    private ?int $nbPage = null;

    #[ORM\ManyToOne( inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Type(type:"App\Entity\Auteur")]
    #[Assert\Valid]
    private ?Auteur $auteur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAnneeParution(): ?\DateTimeInterface
    {
        return $this->anneeParution;
    }

    public function setAnneeParution(\DateTimeInterface $anneeParution): static
    {
        $this->anneeParution = $anneeParution;

        return $this;
    }

    public function getNbPage(): ?int
    {
        return $this->nbPage;
    }

    public function setNbPage(int $nbPage): static
    {
        $this->nbPage = $nbPage;

        return $this;
    }

    public function getAuteur(): ?auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?auteur $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }


}

src/Form/Type/LivreType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Livre;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class)
            ->add('anneeParution', DateType::class)
            ->add('nbPage', IntegerType::class)
            ->add('valider', SubmitType::class);
    }
        // Ici, on défini de manière explicite le « data_class »
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Livre::class,]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Livre;
use App\Entity\Auteur;
use App\Form\Type\LivreType;
use App\Form\Type\AuteurType;
use App\Repository\AuteurRepository;
use App\Repository\LivreRepository; 
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;



#[Route('/livre', requirements: ["_local" => "en|es|fr"], name: "livre_")]
class LivreController extends AbstractController
{
    #[Route('/', name: 'app_livre')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $livres = $entityManager->getRepository(Livre::class)->findAll();
        return $this->render('livre/index.html.twig', [
            'controller_name' => 'LivreController',
            'livres' => $livres,
        ]);
    }

#[Route("/fiche/{id<\d+>}", name: "livre_fiche")]
	public function afficherLivre(int $id, EntityManagerInterface $entityManager): Response
	{
		$livres = $entityManager->getRepository(Livre::class)->find($id);
		if (!$livres) {
			throw $this->createNotFoundException(
			"Aucun livres avec l'id ". $id
			);
		}
		return $this->render('livre/fiche.html.twig', [
            'livres' => $livres,
        ]);
	}

    #[Route("/auteurs/{nb<\d+>}", name: "livre_auteurslivres")]
    public function auteursPlusDeLivres($nb, LivreRepository $livreRepository): Response
    {
        $auteurs = $livreRepository->FindAuteurByNbLivre($nb);
        return $this->render('livre/auteur.html.twig', [
            'auteurs' => $auteurs,
            'nb' => $nb,
        ]);
    }

    #[Route("/compter", name: "livre_compter")]
    public function compter(LivreRepository $livreRepository): Response
    {
        $nbLivres = $livreRepository->getNbLivres();
        return $this->render('livre/livrecompte.html.twig', [
            'nbLivres' => $nbLivres,
        ]);
    }

    #[Route("/titre/{lettre}", name: "livre_titrecommencepar")]
    public function titreCommencePar($lettre, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->getStartBy($lettre);
        return $this->render('livre/lettre.html.twig', [
            'livres' => $livres,
            'lettre' => $lettre,
        ]);
    }

    #[Route("/ajout", name: "livre_ajout")]
    public function ajoutLivre(Request $request, EntityManagerInterface $entityManager)
    {
        // Création d’un objet Livre vierge
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() : pour récupérer les données
            // Les données sont déjà stockées dans la variable d’origine
            // $livre = $form->getData();
            // ... Effectuer le/les traitements(s) à réaliser
            // Par exemple :
            $entityManager->persist($livre);
            $entityManager->flush();
            return $this->redirectToRoute('livre_livre_succes');
        }
        return $this->render('livre/ajout.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/modifier/{id}', name: 'livre_modifier')]
    public function modifierLivre(int $id, Request $request, EntityManagerInterface $entityManager, LivreRepository $livreRepository): Response
    {
        $livre = $livreRepository->find($id);

        if (!$livre) {
            throw $this->createNotFoundException("Livre non trouvé avec l'identifiant : " . $id);
        }

        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_livre_ajout_succes', ['id' => $id]);
        }

        return $this->render('livre/modifier.html.twig', [
            'form' => $form->createView(),
            'livre' => $livre,
        ]);
    }
    

    #[Route('/succes', name: 'livre_succes')]
    public function succes(): Response
    {
        return $this->render('livre/succes.html.twig');
    }

    #[Route("/auteur/ajout", name: "auteur_ajout")]
    public function ajoutAuteur(Request $request, EntityManagerInterface $entityManager)
    {
        // Création d’un objet Livre vierge
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();
            return $this->redirectToRoute('livre_auteur_succes');
        }
        return $this->render('livre/ajout.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    

    #[Route('/auteur/succes', name: 'auteur_succes')]
    public function succesAuteur(): Response
    {
        return $this->render('livre/succes.html.twig');
    }

    #[Route('/auteur/modifier/{id}', name: 'auteur_modifier')]
    public function modifierAuteur(int $id, Request $request, EntityManagerInterface $entityManager, AuteurRepository $auteurRepository): Response
    {
        $auteur = $auteurRepository->find($id);
        
        if (!$auteur) {
            throw $this->createNotFoundException("Auteur non trouvé avec l'identifiant : " . $id);
        }

        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_auteur_succes', ['id' => $id]);
        }

        return $this->render('livre/modifier.html.twig', [
            'form' => $form->createView(),
            'auteur' => $auteur,
        ]);
    }


}

templates/livre/ajout.html.twig
{{ form(form) }}

templates/livre/auteur.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
<link rel="stylesheet" type="text/css" href='{{ asset("css/level3.css") }}'>
<h2>
    Voici les auteurs qui ont écrit plus de {{ nb }} livres :
</h2>

<ul>
    {% for auteur in auteurs %}
        <li>{{auteur.auteur.nom}} ({{ auteur.NbLivres }} livres)</li>
    {% endfor %}
</ul>
{% endblock %}

templates/livre/fiche.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
<style>
    div {
        display: flex;
        flex-direction: column;
        align-items: center;
        font-family: 'Calibri', sans-serif;
    }
    h1{
        color: white;
    }
    table {
      width: 80%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    th, td {
      border: 1px solid #dddddd;
      text-align: center;
      padding: 8px;
    }
    td {
        color: white;
        background-color: blue;
    }
    th {
      background-color: #fff;
    }
</style>
<div>
    <h1>Fiche du livre {{ livres.id }}</h1>
    <table>
        <tr>
            <td>id</td>
            <td>{{ livres.id }}</td>
        </tr>
        <tr>
            <td>titre</td>
            <td>{{ livres.titre }}</td>
        </tr>
        <tr>
            <td>Auteur</td>
            <td>
                {{ livres.auteur.prenom }} {{ livres.auteur.nom }}
            </td>
        </tr>
        <tr>
            <td>date de parution</td>
            <td>{{ livres.AnneeParution|date ("d/m/Y") }}</td>
        </tr>
        <tr>
            <td>nombre de pages</td>
            <td>{{ livres.nbPage }}</td>
        </tr>

    </table>
    <a href='{{ path("livre_app_livre") }}'>RETOUR</a>
</div>

{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
<link rel="stylesheet" type="text/css" href='{{asset("css/level3.css")}}'>
<div>
    <h2>Liste des livres</h2>
    <table>
        <tr>
            <th>id</th>
            <th>titre</th>
            <th>date de parution</th>
            <th>nombre de pages</th>
        </tr>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td><a href="{{ path('livre_livre_fiche', { 'id': livre.id }) }}">{{ livre.titre }}</a></td>
                <td>{{ livre.AnneeParution|date ("d/m/Y") }}</td>
                <td>{{ livre.nbPage }}</td>
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

templates/livre/lettre.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
<link rel="stylesheet" type="text/css" href='{{ asset("css/level3.css") }}'>
    <h2>Livres dont le titre commence par "{{ lettre }}" :</h2>
    <ul>
        {% for livre in livres %}
            <li>{{ livre.titre }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/livre/livrecompte.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
<link rel="stylesheet" type="text/css" href='{{ asset("css/level3.css") }}'>
<h2>
    Nombre total de livres en base : {{ nbLivres }}
</h2>
{% endblock %}

templates/livre/modifier.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}
{{ form(form) }}
<link rel="stylesheet" type="text/css" href='{{ asset("css/form.css") }}'>
{% endblock %}

templates/livre/succes.html.twig
{% extends 'base.html.twig' %}

{% block level3 %}


    <h1>Votre formulaire a été enregistrer mon brave !</h1>
    <a href="{{ path('livre_app_livre') }}">Retour à la liste des livres</a>
{% endblock %}