src/Entity/Caillou.php
<?php

namespace App\Entity;

use App\Repository\CaillouRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CaillouRepository::class)]
class Caillou
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_scientifique = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $rubrique = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNomScientifique(): ?string
    {
        return $this->nom_scientifique;
    }

    public function setNomScientifique(string $nom_scientifique): static
    {
        $this->nom_scientifique = $nom_scientifique;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRubrique(): ?string
    {
        return $this->rubrique;
    }

    public function setRubrique(string $rubrique): static
    {
        $this->rubrique = $rubrique;

        return $this;
    }
}

src/Controller/CaillouController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Caillou;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/caillou', requirements: ["_local" => "en|es|fr"], name: "caillou_")]
class CaillouController extends AbstractController
{
    #[Route('/', name: 'app_caillou')]
    public function index(EntityManagerInterface $entityManager): Response
    {
    	$cailloux = $entityManager->getRepository(Caillou::class)->findAll();
        return $this->render('caillou/index.html.twig', [
            'controller_name' => 'CaillouController',
            'cailloux' => $cailloux,
        ]);
    }

    #[Route("/flore}", name: "caillou_flore")]
	public function flore(EntityManagerInterface $entityManager): Response
    {
    	$cailloux = $entityManager->getRepository(Caillou::class)->findAll();
        return $this->render('caillou/flore.html.twig', [
            'cailloux' => $cailloux,
        ]);
    }
}

templates/caillou/faune.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href='{{asset("css/level3.css")}}'>
{% endblock %}

{% block level3 %}
<div>
    <h2>Les habitant du cailloux !</h2>
    <table>
        <tr>
            <th>id</th>
            <th>nom</th>
            <th>nom scientifique</th>
            <th>image</th>
        </tr>
        {% for caillou in cailloux %}
            <tr>
                <td>{{ caillou.id }}</td>
                <td>{{ caillou.nom }}</td>
                <td>{{ caillou.nomScientifique }}</td>
                <td><img class="cailloux" src="{{ asset( caillou.img) }}" alt="buisson"></td>
            </tr>
        {% endfor %}
    </table>
</div>
</br>


{% endblock %}

templates/caillou/flore.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href='{{asset("css/level3.css")}}'>
{% endblock %}

{% block level3 %}
<div>
    <h2>Les habitant du cailloux !</h2>
    <table>
        <tr>
            <th>id</th>
            <th>nom</th>
            <th>nom scientifique</th>
            <th>image</th>
        </tr>
        {% for caillou in cailloux %}
            <tr>
                <td>{{ caillou.id }}</td>
                <td>{{ caillou.nom }}</td>
                <td>{{ caillou.nomScientifique }}</td>
                <td><img class="cailloux" src="{{ asset( caillou.img) }}" alt="buisson"></td>
            </tr>
        {% endfor %}
    </table>
</div>
</br>


{% endblock %}

templates/caillou/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href='{{asset("css/button.css")}}'>
{% endblock %}

{% block level3 %}
<div>
    <h2>Les habitant du cailloux !</h2>
    </br>
    <div class="container">
  <a class="button" href="#" style="--color:#1e9bff;">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    Faune
  </a>
  <a class="button" href="{{ path('caillou_caillou_flore') }}" style="--color: #ff1867;">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    Flore
  </a>
</div>
</br>


{% endblock %}